[plugin]
repository = "https://github.com/Koenari/HimbeertoniRaidTool.git"
owners = [ "Koenari" ]
project_path = "HimbeertoniRaidTool"
commit = "aa444ad51d805a0bffe7d83aea3cf8cf78fe989c"
changelog = """
New Feature: Automatically switch character in solo tab to currently logged in one
    Bugfix: Ignoring lower ilvl gear works again"""
