[plugin]
repository = "https://github.com/Koenari/HimbeertoniRaidTool.git"
owners = [ "Koenari" ]
project_path = "HimbeertoniRaidTool"
commit = "079166026a0d43282518165466775bd4c763f03a"
changelog = """
General: Updated for 7.2
    General: Home world transfer /name changes of known characters are now automatically applied with gear updates
    System: Some changes to item handling which should reduce size of database files"""
