[plugin]
repository = "https://github.com/Koenari/HimbeertoniRaidTool.git"
owners = [ "Koenari" ]
project_path = "HimbeertoniRaidTool"
commit = "25246e0e9666f146d70857e0208cc2df906e9eb8"
changelog = "New Feature: Stats can now take a party bonus into account (adjust the default in settings)"
