[plugin]
repository = "https://github.com/Koenari/HimbeertoniRaidTool.git"
owners = [ "Koenari" ]
project_path = "HimbeertoniRaidTool"
commit = "e03797e6e4ae61cf6a9f0c6f5cd158cf8f1486ea"
changelog = """
Gear: GearSets now support selection of food. You need to update all set from etro.gg and XivGear.app to get the food
    Configuration: You can trigger updates for all gear sets from the options
    Bugfix: XivGear.app sets now behave as expected (on update and edit)
    System: A lot of changes on underlying systems. If you notice anything behaving strangely let me know via the official discord"""
