[plugin]
repository = "https://github.com/Koenari/HimbeertoniRaidTool.git"
owners = [ "Koenari" ]
project_path = "HimbeertoniRaidTool"
commit = "a6357d0dcb7a3884157b80ab6f9048c0ad57f18c"
changelog = """
Bugfix: Tomestone gear is now displayed properly
    Bugfix: item level coloring works correctly (was off by 10)"""
